### PR TITLE
Adding opacity parameter and trying to fix a bug with getTile function

### PR DESCRIPTION
**Pull request by xavijam**
Further to #194 and #248.

### CODE REVIEW

**Comment by tmcw** [comment]
This implementation of opacity doesn't seem very sturdy. How could opacity be changed after adding the tiles? Can we change it on a parent element, not just tile-by-tile? Should this be in CSS rather than hardcoded, and are there polyfills to handle the ugly IE filters rather than hardcoding them?

**Comment by xavijam** [comment]
I absolutely agree with you, it's not the best choice. I'd like to replicate Leaflet behavior setting the opacity in the parent dom element but didn't find enough time to improve it. Let me review it again.

**Comment by javisantana** [comment]
anyways, maybe we should use ImageMapType which supports opacity ?

https://developers.google.com/maps/documentation/javascript/reference?hl=es#ImageMapType
- looks like I dont understand how pull requests work, why github added more commits to the pull requests?

**Comment by tmcw** [comment]
Yeah, ImageMapType looks good, maybe it does some magic for the png fixing as well.

Pull requests track branches, so if you make one on `master`, any commits you make to master will be automatically added to the request, so it's best to have like a `this-feature` branch just for a pull request and have only the relevant commits on it.

**Comment by tmcw** [comment]
Closing here - happy to merge (and might just be able to look at) a solution that uses ImageMapType instead of MapType. But this branch is currently a bit removed from the specific pull/feature at hand.

**Pull request closed without merging**
