### PR TITLE
Stop propagation of mouse events on tooltip.

### PR DESCRIPTION
**Pull request by KMahoney**
Fixes Leaflet bug with 'close' button.

### CODE REVIEW

**Comment by tmcw** [comment]
This should be addressed on the modest maps side in recent versions; in compliant browsers, MM will confirm that the event target is a map tile before using the event.

**Comment by KMahoney** [comment]
This is also a problem in recent versions of Leaflet.

**Comment by tmcw** [comment]
Ah, Mr. Leaflet. Hmm.

**Comment by KMahoney** [comment]
Perhaps the preferred fix would be to check for a tile in the event callbacks in leaf/interaction.js?

**Comment by tmcw** [comment]
Okay, we should do this, but should use bean instead of rolling our own event utils.

**Comment by willwhite** [comment]
Assigned to [Tender discussion #3175](http://support.mapbox.com/discussions/general-questions/3175-interactive-panel-not-scrolling).

**Pull request closed without merging**
